# Confidential
# Copyright @2019 Zili Wang
# All rights reserved.
# 31154594 Vraagspecificatie simulatiemodel voorspelling wegdekschade
# Any change, update, or development of the file should be notified to wangzilihit@outlook.com



from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimulationTool(object):
    def setupUi(self, SimulationTool):
        SimulationTool.setObjectName("SimulationTool")
        SimulationTool.setWindowModality(QtCore.Qt.NonModal)
        SimulationTool.setEnabled(True)
        SimulationTool.resize(1250, 865)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        SimulationTool.setFont(font)
        SimulationTool.setLocale(QtCore.QLocale(QtCore.QLocale.Dutch, QtCore.QLocale.Netherlands))
        self.centralwidget = QtWidgets.QWidget(SimulationTool)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1251, 311))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("BG.PNG"))
        self.label.setObjectName("label")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setDateRange(QtCore.QDate(2018, 5, 16), QtCore.QDate(2019, 10, 14))
        self.dateEdit.setGeometry(QtCore.QRect(110, 490, 291, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(500, 300, 20, 501))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 820, 1231, 16))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 370, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 460, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 540, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 760, 93, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        #self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        #self.pushButton_2.setGeometry(QtCore.QRect(310, 760, 93, 41))
        #font = QtGui.QFont()
        #font.setFamily("Adobe Devanagari")
        #font.setPointSize(14)
        #font.setBold(True)
        #font.setWeight(75)
        #self.pushButton_2.setFont(font)
        #self.pushButton_2.setObjectName("pushButton_2")

        ## Input in the interface

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(110, 400, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("A15")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 580, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("Rut depth")
        self.comboBox_2.addItem("Roughness")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(110, 670, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("Decision Tree Classifier")



        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 640, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(610, 370, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(610, 400, 551, 211))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setLocale(QtCore.QLocale(QtCore.QLocale.Dutch, QtCore.QLocale.Netherlands))
        self.textBrowser.setObjectName("textBrowser")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(610, 620, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(610, 650, 551, 151))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("C:/Users/Zili Wang/Documents/MSc/future_roughness_2.png"))
        self.label_9.setObjectName("label_9")
        SimulationTool.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SimulationTool)
        self.statusbar.setObjectName("statusbar")
        SimulationTool.setStatusBar(self.statusbar)

        self.retranslateUi(SimulationTool)
        QtCore.QMetaObject.connectSlotsByName(SimulationTool)



    def retranslateUi(self, SimulationTool):
        _translate = QtCore.QCoreApplication.translate
        SimulationTool.setWindowTitle(_translate("SimulationTool", "Simulation Tool of Pavement Performance"))
        SimulationTool.setAccessibleName(_translate("SimulationTool", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("SimulationTool", "Created by Zili Wang (wangzilihit@outlook.com). Copyright@2019 Zili Wang. All rights reserved."))
        self.label_3.setText(_translate("SimulationTool", "Pavement:"))
        self.label_4.setText(_translate("SimulationTool", "Simulation time:"))
        self.label_5.setText(_translate("SimulationTool", "Road performance:"))
        self.pushButton.setText(_translate("SimulationTool", "Run"))
        #self.pushButton_2.setText(_translate("SimulationTool", "Report"))


        self.label_6.setText(_translate("SimulationTool", "Predictive model:"))
        self.label_7.setText(_translate("SimulationTool", "Simulation result:"))
        self.textBrowser.setGeometry(QtCore.QRect(610,400,551,350))
        #self.label_8.setText(_translate("SimulationTool", "Predictive model visualization:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SimulationTool = QtWidgets.QMainWindow()
    ui = Ui_SimulationTool()
    ui.setupUi(SimulationTool)
    SimulationTool.show()
    sys.exit(app.exec_())
